// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/entity_type.proto
// Original file comments:
// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fentity_5ftype_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fentity_5ftype_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2beta1/entity_type.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

// Manages agent entity types.
//
//
// Refer to [documentation](https://dialogflow.com/docs/entities) for more
// # details about entity types.
//
// Standard methods.
class EntityTypes final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2beta1.EntityTypes";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of all entity types in the specified agent.
    virtual ::grpc::Status ListEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>> AsyncListEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>>(AsyncListEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>> PrepareAsyncListEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>>(PrepareAsyncListEntityTypesRaw(context, request, cq));
    }
    // Retrieves the specified entity type.
    virtual ::grpc::Status GetEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::EntityType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>> AsyncGetEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>>(AsyncGetEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>> PrepareAsyncGetEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>>(PrepareAsyncGetEntityTypeRaw(context, request, cq));
    }
    // Creates an entity type in the specified agent.
    virtual ::grpc::Status CreateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::EntityType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>> AsyncCreateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>>(AsyncCreateEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>> PrepareAsyncCreateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>>(PrepareAsyncCreateEntityTypeRaw(context, request, cq));
    }
    // Updates the specified entity type.
    virtual ::grpc::Status UpdateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::EntityType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>> AsyncUpdateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>>(AsyncUpdateEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>> PrepareAsyncUpdateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>>(PrepareAsyncUpdateEntityTypeRaw(context, request, cq));
    }
    // Deletes the specified entity type.
    virtual ::grpc::Status DeleteEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteEntityTypeRaw(context, request, cq));
    }
    // Updates/Creates multiple entity types in the specified agent.
    //
    // Operation <response: [BatchUpdateEntityTypesResponse][google.cloud.dialogflow.v2beta1.BatchUpdateEntityTypesResponse],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchUpdateEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncBatchUpdateEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncBatchUpdateEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncBatchUpdateEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncBatchUpdateEntityTypesRaw(context, request, cq));
    }
    // Deletes entity types in the specified agent.
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchDeleteEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncBatchDeleteEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncBatchDeleteEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncBatchDeleteEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncBatchDeleteEntityTypesRaw(context, request, cq));
    }
    // Creates multiple new entities in the specified entity type (extends the
    // existing collection of entries).
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty]>
    virtual ::grpc::Status BatchCreateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncBatchCreateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncBatchCreateEntitiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncBatchCreateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncBatchCreateEntitiesRaw(context, request, cq));
    }
    // Updates entities in the specified entity type (replaces the existing
    // collection of entries).
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchUpdateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncBatchUpdateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncBatchUpdateEntitiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncBatchUpdateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncBatchUpdateEntitiesRaw(context, request, cq));
    }
    // Deletes entities in the specified entity type.
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchDeleteEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncBatchDeleteEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncBatchDeleteEntitiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncBatchDeleteEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncBatchDeleteEntitiesRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>* AsyncListEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>* PrepareAsyncListEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>* AsyncGetEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>* PrepareAsyncGetEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>* AsyncCreateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>* PrepareAsyncCreateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>* AsyncUpdateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::EntityType>* PrepareAsyncUpdateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncBatchUpdateEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncBatchUpdateEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncBatchDeleteEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncBatchDeleteEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncBatchCreateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncBatchCreateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncBatchUpdateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncBatchUpdateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncBatchDeleteEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncBatchDeleteEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ListEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>> AsyncListEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>>(AsyncListEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>> PrepareAsyncListEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>>(PrepareAsyncListEntityTypesRaw(context, request, cq));
    }
    ::grpc::Status GetEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::EntityType* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>> AsyncGetEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>>(AsyncGetEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>> PrepareAsyncGetEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>>(PrepareAsyncGetEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status CreateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::EntityType* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>> AsyncCreateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>>(AsyncCreateEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>> PrepareAsyncCreateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>>(PrepareAsyncCreateEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status UpdateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::EntityType* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>> AsyncUpdateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>>(AsyncUpdateEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>> PrepareAsyncUpdateEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>>(PrepareAsyncUpdateEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status DeleteEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status BatchUpdateEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncBatchUpdateEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncBatchUpdateEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncBatchUpdateEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncBatchUpdateEntityTypesRaw(context, request, cq));
    }
    ::grpc::Status BatchDeleteEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncBatchDeleteEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncBatchDeleteEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncBatchDeleteEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncBatchDeleteEntityTypesRaw(context, request, cq));
    }
    ::grpc::Status BatchCreateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncBatchCreateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncBatchCreateEntitiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncBatchCreateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncBatchCreateEntitiesRaw(context, request, cq));
    }
    ::grpc::Status BatchUpdateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncBatchUpdateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncBatchUpdateEntitiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncBatchUpdateEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncBatchUpdateEntitiesRaw(context, request, cq));
    }
    ::grpc::Status BatchDeleteEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncBatchDeleteEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncBatchDeleteEntitiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncBatchDeleteEntities(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncBatchDeleteEntitiesRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>* AsyncListEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>* PrepareAsyncListEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>* AsyncGetEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>* PrepareAsyncGetEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>* AsyncCreateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>* PrepareAsyncCreateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>* AsyncUpdateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::EntityType>* PrepareAsyncUpdateEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncBatchUpdateEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncBatchUpdateEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncBatchDeleteEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncBatchDeleteEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncBatchCreateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncBatchCreateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncBatchUpdateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncBatchUpdateEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncBatchDeleteEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncBatchDeleteEntitiesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListEntityTypes_;
    const ::grpc::internal::RpcMethod rpcmethod_GetEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchUpdateEntityTypes_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchDeleteEntityTypes_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchCreateEntities_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchUpdateEntities_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchDeleteEntities_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of all entity types in the specified agent.
    virtual ::grpc::Status ListEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse* response);
    // Retrieves the specified entity type.
    virtual ::grpc::Status GetEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response);
    // Creates an entity type in the specified agent.
    virtual ::grpc::Status CreateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response);
    // Updates the specified entity type.
    virtual ::grpc::Status UpdateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response);
    // Deletes the specified entity type.
    virtual ::grpc::Status DeleteEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest* request, ::google::protobuf::Empty* response);
    // Updates/Creates multiple entity types in the specified agent.
    //
    // Operation <response: [BatchUpdateEntityTypesResponse][google.cloud.dialogflow.v2beta1.BatchUpdateEntityTypesResponse],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchUpdateEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest* request, ::google::longrunning::Operation* response);
    // Deletes entity types in the specified agent.
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchDeleteEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest* request, ::google::longrunning::Operation* response);
    // Creates multiple new entities in the specified entity type (extends the
    // existing collection of entries).
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty]>
    virtual ::grpc::Status BatchCreateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest* request, ::google::longrunning::Operation* response);
    // Updates entities in the specified entity type (replaces the existing
    // collection of entries).
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchUpdateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest* request, ::google::longrunning::Operation* response);
    // Deletes entities in the specified entity type.
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status BatchDeleteEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest* request, ::google::longrunning::Operation* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ListEntityTypes() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListEntityTypes(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetEntityType() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::EntityType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateEntityType() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::EntityType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateEntityType() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::EntityType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteEntityType() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchUpdateEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BatchUpdateEntityTypes() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_BatchUpdateEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchUpdateEntityTypes(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchDeleteEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BatchDeleteEntityTypes() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_BatchDeleteEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDeleteEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchDeleteEntityTypes(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchCreateEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BatchCreateEntities() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_BatchCreateEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchCreateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchCreateEntities(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchUpdateEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BatchUpdateEntities() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_BatchUpdateEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchUpdateEntities(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchDeleteEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BatchDeleteEntities() {
      ::grpc::Service::MarkMethodAsync(9);
    }
    ~WithAsyncMethod_BatchDeleteEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDeleteEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchDeleteEntities(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(9, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListEntityTypes<WithAsyncMethod_GetEntityType<WithAsyncMethod_CreateEntityType<WithAsyncMethod_UpdateEntityType<WithAsyncMethod_DeleteEntityType<WithAsyncMethod_BatchUpdateEntityTypes<WithAsyncMethod_BatchDeleteEntityTypes<WithAsyncMethod_BatchCreateEntities<WithAsyncMethod_BatchUpdateEntities<WithAsyncMethod_BatchDeleteEntities<Service > > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ListEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ListEntityTypes() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetEntityType() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateEntityType() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateEntityType() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteEntityType() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchUpdateEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BatchUpdateEntityTypes() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_BatchUpdateEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchDeleteEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BatchDeleteEntityTypes() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_BatchDeleteEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDeleteEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchCreateEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BatchCreateEntities() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_BatchCreateEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchCreateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchUpdateEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BatchUpdateEntities() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_BatchUpdateEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchDeleteEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BatchDeleteEntities() {
      ::grpc::Service::MarkMethodGeneric(9);
    }
    ~WithGenericMethod_BatchDeleteEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDeleteEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ListEntityTypes() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>(std::bind(&WithStreamedUnaryMethod_ListEntityTypes<BaseClass>::StreamedListEntityTypes, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ListEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListEntityTypes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::ListEntityTypesRequest,::google::cloud::dialogflow::v2beta1::ListEntityTypesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetEntityType() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::EntityType>(std::bind(&WithStreamedUnaryMethod_GetEntityType<BaseClass>::StreamedGetEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::GetEntityTypeRequest,::google::cloud::dialogflow::v2beta1::EntityType>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CreateEntityType() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::EntityType>(std::bind(&WithStreamedUnaryMethod_CreateEntityType<BaseClass>::StreamedCreateEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CreateEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::CreateEntityTypeRequest,::google::cloud::dialogflow::v2beta1::EntityType>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_UpdateEntityType() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::EntityType>(std::bind(&WithStreamedUnaryMethod_UpdateEntityType<BaseClass>::StreamedUpdateEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_UpdateEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::EntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::UpdateEntityTypeRequest,::google::cloud::dialogflow::v2beta1::EntityType>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_DeleteEntityType() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest, ::google::protobuf::Empty>(std::bind(&WithStreamedUnaryMethod_DeleteEntityType<BaseClass>::StreamedDeleteEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_DeleteEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::DeleteEntityTypeRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchUpdateEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_BatchUpdateEntityTypes() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_BatchUpdateEntityTypes<BaseClass>::StreamedBatchUpdateEntityTypes, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_BatchUpdateEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchUpdateEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchUpdateEntityTypes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::BatchUpdateEntityTypesRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchDeleteEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_BatchDeleteEntityTypes() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_BatchDeleteEntityTypes<BaseClass>::StreamedBatchDeleteEntityTypes, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_BatchDeleteEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchDeleteEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchDeleteEntityTypes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::BatchDeleteEntityTypesRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchCreateEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_BatchCreateEntities() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_BatchCreateEntities<BaseClass>::StreamedBatchCreateEntities, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_BatchCreateEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchCreateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchCreateEntities(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::BatchCreateEntitiesRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchUpdateEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_BatchUpdateEntities() {
      ::grpc::Service::MarkMethodStreamed(8,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_BatchUpdateEntities<BaseClass>::StreamedBatchUpdateEntities, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_BatchUpdateEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchUpdateEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchUpdateEntities(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::BatchUpdateEntitiesRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchDeleteEntities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_BatchDeleteEntities() {
      ::grpc::Service::MarkMethodStreamed(9,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_BatchDeleteEntities<BaseClass>::StreamedBatchDeleteEntities, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_BatchDeleteEntities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchDeleteEntities(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchDeleteEntities(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::BatchDeleteEntitiesRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListEntityTypes<WithStreamedUnaryMethod_GetEntityType<WithStreamedUnaryMethod_CreateEntityType<WithStreamedUnaryMethod_UpdateEntityType<WithStreamedUnaryMethod_DeleteEntityType<WithStreamedUnaryMethod_BatchUpdateEntityTypes<WithStreamedUnaryMethod_BatchDeleteEntityTypes<WithStreamedUnaryMethod_BatchCreateEntities<WithStreamedUnaryMethod_BatchUpdateEntities<WithStreamedUnaryMethod_BatchDeleteEntities<Service > > > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListEntityTypes<WithStreamedUnaryMethod_GetEntityType<WithStreamedUnaryMethod_CreateEntityType<WithStreamedUnaryMethod_UpdateEntityType<WithStreamedUnaryMethod_DeleteEntityType<WithStreamedUnaryMethod_BatchUpdateEntityTypes<WithStreamedUnaryMethod_BatchDeleteEntityTypes<WithStreamedUnaryMethod_BatchCreateEntities<WithStreamedUnaryMethod_BatchUpdateEntities<WithStreamedUnaryMethod_BatchDeleteEntities<Service > > > > > > > > > > StreamedService;
};

}  // namespace v2beta1
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fentity_5ftype_2eproto__INCLUDED
