// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/intent.proto

#include "google/cloud/dialogflow/v2beta1/intent.pb.h"
#include "google/cloud/dialogflow/v2beta1/intent.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

static const char* Intents_method_names[] = {
  "/google.cloud.dialogflow.v2beta1.Intents/ListIntents",
  "/google.cloud.dialogflow.v2beta1.Intents/GetIntent",
  "/google.cloud.dialogflow.v2beta1.Intents/CreateIntent",
  "/google.cloud.dialogflow.v2beta1.Intents/UpdateIntent",
  "/google.cloud.dialogflow.v2beta1.Intents/DeleteIntent",
  "/google.cloud.dialogflow.v2beta1.Intents/BatchUpdateIntents",
  "/google.cloud.dialogflow.v2beta1.Intents/BatchDeleteIntents",
};

std::unique_ptr< Intents::Stub> Intents::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Intents::Stub> stub(new Intents::Stub(channel));
  return stub;
}

Intents::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ListIntents_(Intents_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetIntent_(Intents_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateIntent_(Intents_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateIntent_(Intents_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteIntent_(Intents_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchUpdateIntents_(Intents_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchDeleteIntents_(Intents_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Intents::Stub::ListIntents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListIntentsRequest& request, ::google::cloud::dialogflow::v2beta1::ListIntentsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListIntents_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListIntentsResponse>* Intents::Stub::AsyncListIntentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::ListIntentsResponse>::Create(channel_.get(), cq, rpcmethod_ListIntents_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListIntentsResponse>* Intents::Stub::PrepareAsyncListIntentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::ListIntentsResponse>::Create(channel_.get(), cq, rpcmethod_ListIntents_, context, request, false);
}

::grpc::Status Intents::Stub::GetIntent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetIntentRequest& request, ::google::cloud::dialogflow::v2beta1::Intent* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetIntent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Intent>* Intents::Stub::AsyncGetIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::Intent>::Create(channel_.get(), cq, rpcmethod_GetIntent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Intent>* Intents::Stub::PrepareAsyncGetIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::Intent>::Create(channel_.get(), cq, rpcmethod_GetIntent_, context, request, false);
}

::grpc::Status Intents::Stub::CreateIntent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateIntentRequest& request, ::google::cloud::dialogflow::v2beta1::Intent* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateIntent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Intent>* Intents::Stub::AsyncCreateIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::Intent>::Create(channel_.get(), cq, rpcmethod_CreateIntent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Intent>* Intents::Stub::PrepareAsyncCreateIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::Intent>::Create(channel_.get(), cq, rpcmethod_CreateIntent_, context, request, false);
}

::grpc::Status Intents::Stub::UpdateIntent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateIntentRequest& request, ::google::cloud::dialogflow::v2beta1::Intent* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateIntent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Intent>* Intents::Stub::AsyncUpdateIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::Intent>::Create(channel_.get(), cq, rpcmethod_UpdateIntent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Intent>* Intents::Stub::PrepareAsyncUpdateIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::Intent>::Create(channel_.get(), cq, rpcmethod_UpdateIntent_, context, request, false);
}

::grpc::Status Intents::Stub::DeleteIntent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteIntentRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteIntent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Intents::Stub::AsyncDeleteIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::protobuf::Empty>::Create(channel_.get(), cq, rpcmethod_DeleteIntent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Intents::Stub::PrepareAsyncDeleteIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::protobuf::Empty>::Create(channel_.get(), cq, rpcmethod_DeleteIntent_, context, request, false);
}

::grpc::Status Intents::Stub::BatchUpdateIntents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateIntentsRequest& request, ::google::longrunning::Operation* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BatchUpdateIntents_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* Intents::Stub::AsyncBatchUpdateIntentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::longrunning::Operation>::Create(channel_.get(), cq, rpcmethod_BatchUpdateIntents_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* Intents::Stub::PrepareAsyncBatchUpdateIntentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::longrunning::Operation>::Create(channel_.get(), cq, rpcmethod_BatchUpdateIntents_, context, request, false);
}

::grpc::Status Intents::Stub::BatchDeleteIntents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteIntentsRequest& request, ::google::longrunning::Operation* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BatchDeleteIntents_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* Intents::Stub::AsyncBatchDeleteIntentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::longrunning::Operation>::Create(channel_.get(), cq, rpcmethod_BatchDeleteIntents_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* Intents::Stub::PrepareAsyncBatchDeleteIntentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::longrunning::Operation>::Create(channel_.get(), cq, rpcmethod_BatchDeleteIntents_, context, request, false);
}

Intents::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::ListIntentsRequest, ::google::cloud::dialogflow::v2beta1::ListIntentsResponse>(
          std::mem_fn(&Intents::Service::ListIntents), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::GetIntentRequest, ::google::cloud::dialogflow::v2beta1::Intent>(
          std::mem_fn(&Intents::Service::GetIntent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::CreateIntentRequest, ::google::cloud::dialogflow::v2beta1::Intent>(
          std::mem_fn(&Intents::Service::CreateIntent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::UpdateIntentRequest, ::google::cloud::dialogflow::v2beta1::Intent>(
          std::mem_fn(&Intents::Service::UpdateIntent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::DeleteIntentRequest, ::google::protobuf::Empty>(
          std::mem_fn(&Intents::Service::DeleteIntent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::BatchUpdateIntentsRequest, ::google::longrunning::Operation>(
          std::mem_fn(&Intents::Service::BatchUpdateIntents), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Intents_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Intents::Service, ::google::cloud::dialogflow::v2beta1::BatchDeleteIntentsRequest, ::google::longrunning::Operation>(
          std::mem_fn(&Intents::Service::BatchDeleteIntents), this)));
}

Intents::Service::~Service() {
}

::grpc::Status Intents::Service::ListIntents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListIntentsRequest* request, ::google::cloud::dialogflow::v2beta1::ListIntentsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Intents::Service::GetIntent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetIntentRequest* request, ::google::cloud::dialogflow::v2beta1::Intent* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Intents::Service::CreateIntent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateIntentRequest* request, ::google::cloud::dialogflow::v2beta1::Intent* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Intents::Service::UpdateIntent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateIntentRequest* request, ::google::cloud::dialogflow::v2beta1::Intent* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Intents::Service::DeleteIntent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteIntentRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Intents::Service::BatchUpdateIntents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchUpdateIntentsRequest* request, ::google::longrunning::Operation* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Intents::Service::BatchDeleteIntents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::BatchDeleteIntentsRequest* request, ::google::longrunning::Operation* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace google
}  // namespace cloud
}  // namespace dialogflow
}  // namespace v2beta1

