// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/session_entity_type.proto

#include "google/cloud/dialogflow/v2beta1/session_entity_type.pb.h"
#include "google/cloud/dialogflow/v2beta1/session_entity_type.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

static const char* SessionEntityTypes_method_names[] = {
  "/google.cloud.dialogflow.v2beta1.SessionEntityTypes/ListSessionEntityTypes",
  "/google.cloud.dialogflow.v2beta1.SessionEntityTypes/GetSessionEntityType",
  "/google.cloud.dialogflow.v2beta1.SessionEntityTypes/CreateSessionEntityType",
  "/google.cloud.dialogflow.v2beta1.SessionEntityTypes/UpdateSessionEntityType",
  "/google.cloud.dialogflow.v2beta1.SessionEntityTypes/DeleteSessionEntityType",
};

std::unique_ptr< SessionEntityTypes::Stub> SessionEntityTypes::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SessionEntityTypes::Stub> stub(new SessionEntityTypes::Stub(channel));
  return stub;
}

SessionEntityTypes::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ListSessionEntityTypes_(SessionEntityTypes_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSessionEntityType_(SessionEntityTypes_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateSessionEntityType_(SessionEntityTypes_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateSessionEntityType_(SessionEntityTypes_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteSessionEntityType_(SessionEntityTypes_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SessionEntityTypes::Stub::ListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListSessionEntityTypes_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* SessionEntityTypes::Stub::AsyncListSessionEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>::Create(channel_.get(), cq, rpcmethod_ListSessionEntityTypes_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* SessionEntityTypes::Stub::PrepareAsyncListSessionEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>::Create(channel_.get(), cq, rpcmethod_ListSessionEntityTypes_, context, request, false);
}

::grpc::Status SessionEntityTypes::Stub::GetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetSessionEntityType_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* SessionEntityTypes::Stub::AsyncGetSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::SessionEntityType>::Create(channel_.get(), cq, rpcmethod_GetSessionEntityType_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* SessionEntityTypes::Stub::PrepareAsyncGetSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::SessionEntityType>::Create(channel_.get(), cq, rpcmethod_GetSessionEntityType_, context, request, false);
}

::grpc::Status SessionEntityTypes::Stub::CreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateSessionEntityType_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* SessionEntityTypes::Stub::AsyncCreateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::SessionEntityType>::Create(channel_.get(), cq, rpcmethod_CreateSessionEntityType_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* SessionEntityTypes::Stub::PrepareAsyncCreateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::SessionEntityType>::Create(channel_.get(), cq, rpcmethod_CreateSessionEntityType_, context, request, false);
}

::grpc::Status SessionEntityTypes::Stub::UpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateSessionEntityType_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* SessionEntityTypes::Stub::AsyncUpdateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::SessionEntityType>::Create(channel_.get(), cq, rpcmethod_UpdateSessionEntityType_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* SessionEntityTypes::Stub::PrepareAsyncUpdateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2beta1::SessionEntityType>::Create(channel_.get(), cq, rpcmethod_UpdateSessionEntityType_, context, request, false);
}

::grpc::Status SessionEntityTypes::Stub::DeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteSessionEntityType_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* SessionEntityTypes::Stub::AsyncDeleteSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::protobuf::Empty>::Create(channel_.get(), cq, rpcmethod_DeleteSessionEntityType_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* SessionEntityTypes::Stub::PrepareAsyncDeleteSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::protobuf::Empty>::Create(channel_.get(), cq, rpcmethod_DeleteSessionEntityType_, context, request, false);
}

SessionEntityTypes::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionEntityTypes_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionEntityTypes::Service, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>(
          std::mem_fn(&SessionEntityTypes::Service::ListSessionEntityTypes), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionEntityTypes_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionEntityTypes::Service, ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::SessionEntityType>(
          std::mem_fn(&SessionEntityTypes::Service::GetSessionEntityType), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionEntityTypes_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionEntityTypes::Service, ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::SessionEntityType>(
          std::mem_fn(&SessionEntityTypes::Service::CreateSessionEntityType), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionEntityTypes_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionEntityTypes::Service, ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::SessionEntityType>(
          std::mem_fn(&SessionEntityTypes::Service::UpdateSessionEntityType), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionEntityTypes_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionEntityTypes::Service, ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest, ::google::protobuf::Empty>(
          std::mem_fn(&SessionEntityTypes::Service::DeleteSessionEntityType), this)));
}

SessionEntityTypes::Service::~Service() {
}

::grpc::Status SessionEntityTypes::Service::ListSessionEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionEntityTypes::Service::GetSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionEntityTypes::Service::CreateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionEntityTypes::Service::UpdateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionEntityTypes::Service::DeleteSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace google
}  // namespace cloud
}  // namespace dialogflow
}  // namespace v2beta1

