// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/session_entity_type.proto
// Original file comments:
// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fsession_5fentity_5ftype_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fsession_5fentity_5ftype_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2beta1/session_entity_type.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

// Manages session entity types.
//
// Session entity types can be redefined on a session level, allowing for
// specific concepts, like a user's playlists.
//
//
// Standard methods.
class SessionEntityTypes final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2beta1.SessionEntityTypes";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of all session entity types in the specified session.
    virtual ::grpc::Status ListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>> AsyncListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>>(AsyncListSessionEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>> PrepareAsyncListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>>(PrepareAsyncListSessionEntityTypesRaw(context, request, cq));
    }
    // Retrieves the specified session entity type.
    virtual ::grpc::Status GetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> AsyncGetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(AsyncGetSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> PrepareAsyncGetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(PrepareAsyncGetSessionEntityTypeRaw(context, request, cq));
    }
    // Creates a session entity type.
    virtual ::grpc::Status CreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> AsyncCreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(AsyncCreateSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> PrepareAsyncCreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(PrepareAsyncCreateSessionEntityTypeRaw(context, request, cq));
    }
    // Updates the specified session entity type.
    virtual ::grpc::Status UpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> AsyncUpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(AsyncUpdateSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> PrepareAsyncUpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(PrepareAsyncUpdateSessionEntityTypeRaw(context, request, cq));
    }
    // Deletes the specified session entity type.
    virtual ::grpc::Status DeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteSessionEntityTypeRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* AsyncListSessionEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* PrepareAsyncListSessionEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* AsyncGetSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* PrepareAsyncGetSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* AsyncCreateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* PrepareAsyncCreateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* AsyncUpdateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* PrepareAsyncUpdateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>> AsyncListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>>(AsyncListSessionEntityTypesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>> PrepareAsyncListSessionEntityTypes(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>>(PrepareAsyncListSessionEntityTypesRaw(context, request, cq));
    }
    ::grpc::Status GetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> AsyncGetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(AsyncGetSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> PrepareAsyncGetSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(PrepareAsyncGetSessionEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status CreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> AsyncCreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(AsyncCreateSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> PrepareAsyncCreateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(PrepareAsyncCreateSessionEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status UpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> AsyncUpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(AsyncUpdateSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>> PrepareAsyncUpdateSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>>(PrepareAsyncUpdateSessionEntityTypeRaw(context, request, cq));
    }
    ::grpc::Status DeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteSessionEntityTypeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteSessionEntityType(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteSessionEntityTypeRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* AsyncListSessionEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* PrepareAsyncListSessionEntityTypesRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* AsyncGetSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* PrepareAsyncGetSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* AsyncCreateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* PrepareAsyncCreateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* AsyncUpdateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* PrepareAsyncUpdateSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteSessionEntityTypeRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListSessionEntityTypes_;
    const ::grpc::internal::RpcMethod rpcmethod_GetSessionEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateSessionEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateSessionEntityType_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteSessionEntityType_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of all session entity types in the specified session.
    virtual ::grpc::Status ListSessionEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response);
    // Retrieves the specified session entity type.
    virtual ::grpc::Status GetSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response);
    // Creates a session entity type.
    virtual ::grpc::Status CreateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response);
    // Updates the specified session entity type.
    virtual ::grpc::Status UpdateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response);
    // Deletes the specified session entity type.
    virtual ::grpc::Status DeleteSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListSessionEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ListSessionEntityTypes() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListSessionEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSessionEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSessionEntityTypes(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetSessionEntityType() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSessionEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateSessionEntityType() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateSessionEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateSessionEntityType() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSessionEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::SessionEntityType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteSessionEntityType() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteSessionEntityType(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListSessionEntityTypes<WithAsyncMethod_GetSessionEntityType<WithAsyncMethod_CreateSessionEntityType<WithAsyncMethod_UpdateSessionEntityType<WithAsyncMethod_DeleteSessionEntityType<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ListSessionEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ListSessionEntityTypes() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListSessionEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSessionEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetSessionEntityType() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateSessionEntityType() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateSessionEntityType() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteSessionEntityType() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListSessionEntityTypes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ListSessionEntityTypes() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>(std::bind(&WithStreamedUnaryMethod_ListSessionEntityTypes<BaseClass>::StreamedListSessionEntityTypes, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ListSessionEntityTypes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListSessionEntityTypes(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest* request, ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListSessionEntityTypes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesRequest,::google::cloud::dialogflow::v2beta1::ListSessionEntityTypesResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetSessionEntityType() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::SessionEntityType>(std::bind(&WithStreamedUnaryMethod_GetSessionEntityType<BaseClass>::StreamedGetSessionEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSessionEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::GetSessionEntityTypeRequest,::google::cloud::dialogflow::v2beta1::SessionEntityType>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CreateSessionEntityType() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::SessionEntityType>(std::bind(&WithStreamedUnaryMethod_CreateSessionEntityType<BaseClass>::StreamedCreateSessionEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CreateSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateSessionEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::CreateSessionEntityTypeRequest,::google::cloud::dialogflow::v2beta1::SessionEntityType>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_UpdateSessionEntityType() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest, ::google::cloud::dialogflow::v2beta1::SessionEntityType>(std::bind(&WithStreamedUnaryMethod_UpdateSessionEntityType<BaseClass>::StreamedUpdateSessionEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_UpdateSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest* request, ::google::cloud::dialogflow::v2beta1::SessionEntityType* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateSessionEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::UpdateSessionEntityTypeRequest,::google::cloud::dialogflow::v2beta1::SessionEntityType>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteSessionEntityType : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_DeleteSessionEntityType() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest, ::google::protobuf::Empty>(std::bind(&WithStreamedUnaryMethod_DeleteSessionEntityType<BaseClass>::StreamedDeleteSessionEntityType, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_DeleteSessionEntityType() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteSessionEntityType(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteSessionEntityType(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::DeleteSessionEntityTypeRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListSessionEntityTypes<WithStreamedUnaryMethod_GetSessionEntityType<WithStreamedUnaryMethod_CreateSessionEntityType<WithStreamedUnaryMethod_UpdateSessionEntityType<WithStreamedUnaryMethod_DeleteSessionEntityType<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListSessionEntityTypes<WithStreamedUnaryMethod_GetSessionEntityType<WithStreamedUnaryMethod_CreateSessionEntityType<WithStreamedUnaryMethod_UpdateSessionEntityType<WithStreamedUnaryMethod_DeleteSessionEntityType<Service > > > > > StreamedService;
};

}  // namespace v2beta1
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fsession_5fentity_5ftype_2eproto__INCLUDED
