// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/tier.proto
// Original file comments:
// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2ftier_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2ftier_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2beta1/tier.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

// # Manages agent tier.
//
// Standard methods.
class Tiers final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2beta1.Tiers";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Retrieves the tier of the specified agent.
    virtual ::grpc::Status GetAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>> AsyncGetAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>>(AsyncGetAgentTierRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>> PrepareAsyncGetAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>>(PrepareAsyncGetAgentTierRaw(context, request, cq));
    }
    // Updates the tier of the specified agent.
    virtual ::grpc::Status UpdateAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>> AsyncUpdateAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>>(AsyncUpdateAgentTierRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>> PrepareAsyncUpdateAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>>(PrepareAsyncUpdateAgentTierRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>* AsyncGetAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>* PrepareAsyncGetAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>* AsyncUpdateAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::AgentTier>* PrepareAsyncUpdateAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>> AsyncGetAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>>(AsyncGetAgentTierRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>> PrepareAsyncGetAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>>(PrepareAsyncGetAgentTierRaw(context, request, cq));
    }
    ::grpc::Status UpdateAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>> AsyncUpdateAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>>(AsyncUpdateAgentTierRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>> PrepareAsyncUpdateAgentTier(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>>(PrepareAsyncUpdateAgentTierRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>* AsyncGetAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>* PrepareAsyncGetAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>* AsyncUpdateAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::AgentTier>* PrepareAsyncUpdateAgentTierRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetAgentTier_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateAgentTier_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Retrieves the tier of the specified agent.
    virtual ::grpc::Status GetAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response);
    // Updates the tier of the specified agent.
    virtual ::grpc::Status UpdateAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAgentTier : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetAgentTier() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetAgentTier() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAgentTier(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::AgentTier>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateAgentTier : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateAgentTier() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_UpdateAgentTier() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateAgentTier(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::AgentTier>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetAgentTier<WithAsyncMethod_UpdateAgentTier<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetAgentTier : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetAgentTier() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetAgentTier() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateAgentTier : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateAgentTier() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_UpdateAgentTier() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAgentTier : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetAgentTier() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest, ::google::cloud::dialogflow::v2beta1::AgentTier>(std::bind(&WithStreamedUnaryMethod_GetAgentTier<BaseClass>::StreamedGetAgentTier, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetAgentTier() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAgentTier(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::GetAgentTierRequest,::google::cloud::dialogflow::v2beta1::AgentTier>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateAgentTier : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_UpdateAgentTier() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest, ::google::cloud::dialogflow::v2beta1::AgentTier>(std::bind(&WithStreamedUnaryMethod_UpdateAgentTier<BaseClass>::StreamedUpdateAgentTier, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_UpdateAgentTier() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateAgentTier(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest* request, ::google::cloud::dialogflow::v2beta1::AgentTier* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateAgentTier(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::UpdateAgentTierRequest,::google::cloud::dialogflow::v2beta1::AgentTier>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetAgentTier<WithStreamedUnaryMethod_UpdateAgentTier<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetAgentTier<WithStreamedUnaryMethod_UpdateAgentTier<Service > > StreamedService;
};

}  // namespace v2beta1
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2ftier_2eproto__INCLUDED
