// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/agent.proto
// Original file comments:
// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fagent_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fagent_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2beta1/agent.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

// Manages conversational agents.
//
//
// Refer to [documentation](https://dialogflow.com/docs/agents) for more details
// # about agents.
//
// Standard methods.
class Agents final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2beta1.Agents";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Retrieves the specified agent.
    virtual ::grpc::Status GetAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::google::cloud::dialogflow::v2beta1::Agent* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Agent>> AsyncGetAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Agent>>(AsyncGetAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Agent>> PrepareAsyncGetAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Agent>>(PrepareAsyncGetAgentRaw(context, request, cq));
    }
    // Returns the list of agents.
    //
    // Since there is at most one conversational agent per project, this method is
    // useful primarily for listing all agents across projects the caller has
    // access to. One can achieve that with a wildcard project collection id "-".
    // Refer to [List
    // Sub-Collections](https://cloud.google.com/apis/design/design_patterns#list_sub-collections).
    virtual ::grpc::Status SearchAgents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>> AsyncSearchAgents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>>(AsyncSearchAgentsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>> PrepareAsyncSearchAgents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>>(PrepareAsyncSearchAgentsRaw(context, request, cq));
    }
    // Trains the specified agent.
    //
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status TrainAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncTrainAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncTrainAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncTrainAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncTrainAgentRaw(context, request, cq));
    }
    // Exports the specified agent to a ZIP file.
    //
    //
    // Operation <response: [ExportAgentResponse][google.cloud.dialogflow.v2beta1.ExportAgentResponse],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status ExportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncExportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncExportAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncExportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncExportAgentRaw(context, request, cq));
    }
    // Imports the specified agent from a ZIP file.
    //
    // Uploads new intents and entity types without deleting the existing ones.
    // Intents and entity types with the same name are replaced with the new
    // versions from ImportAgentRequest.
    //
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status ImportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncImportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncImportAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncImportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncImportAgentRaw(context, request, cq));
    }
    // Restores the specified agent from a ZIP file.
    //
    // Replaces the current agent version with a new one. All the intents and
    // entity types in the older version are deleted.
    //
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status RestoreAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncRestoreAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncRestoreAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> PrepareAsyncRestoreAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(PrepareAsyncRestoreAgentRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Agent>* AsyncGetAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Agent>* PrepareAsyncGetAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>* AsyncSearchAgentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>* PrepareAsyncSearchAgentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncTrainAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncTrainAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncExportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncExportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncImportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncImportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncRestoreAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* PrepareAsyncRestoreAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::google::cloud::dialogflow::v2beta1::Agent* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Agent>> AsyncGetAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Agent>>(AsyncGetAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Agent>> PrepareAsyncGetAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Agent>>(PrepareAsyncGetAgentRaw(context, request, cq));
    }
    ::grpc::Status SearchAgents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>> AsyncSearchAgents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>>(AsyncSearchAgentsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>> PrepareAsyncSearchAgents(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>>(PrepareAsyncSearchAgentsRaw(context, request, cq));
    }
    ::grpc::Status TrainAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncTrainAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncTrainAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncTrainAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncTrainAgentRaw(context, request, cq));
    }
    ::grpc::Status ExportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncExportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncExportAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncExportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncExportAgentRaw(context, request, cq));
    }
    ::grpc::Status ImportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncImportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncImportAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncImportAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncImportAgentRaw(context, request, cq));
    }
    ::grpc::Status RestoreAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::google::longrunning::Operation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncRestoreAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncRestoreAgentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> PrepareAsyncRestoreAgent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(PrepareAsyncRestoreAgentRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Agent>* AsyncGetAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Agent>* PrepareAsyncGetAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>* AsyncSearchAgentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>* PrepareAsyncSearchAgentsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncTrainAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncTrainAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncExportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncExportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncImportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncImportAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncRestoreAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* PrepareAsyncRestoreAgentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetAgent_;
    const ::grpc::internal::RpcMethod rpcmethod_SearchAgents_;
    const ::grpc::internal::RpcMethod rpcmethod_TrainAgent_;
    const ::grpc::internal::RpcMethod rpcmethod_ExportAgent_;
    const ::grpc::internal::RpcMethod rpcmethod_ImportAgent_;
    const ::grpc::internal::RpcMethod rpcmethod_RestoreAgent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Retrieves the specified agent.
    virtual ::grpc::Status GetAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest* request, ::google::cloud::dialogflow::v2beta1::Agent* response);
    // Returns the list of agents.
    //
    // Since there is at most one conversational agent per project, this method is
    // useful primarily for listing all agents across projects the caller has
    // access to. One can achieve that with a wildcard project collection id "-".
    // Refer to [List
    // Sub-Collections](https://cloud.google.com/apis/design/design_patterns#list_sub-collections).
    virtual ::grpc::Status SearchAgents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest* request, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse* response);
    // Trains the specified agent.
    //
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status TrainAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest* request, ::google::longrunning::Operation* response);
    // Exports the specified agent to a ZIP file.
    //
    //
    // Operation <response: [ExportAgentResponse][google.cloud.dialogflow.v2beta1.ExportAgentResponse],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status ExportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest* request, ::google::longrunning::Operation* response);
    // Imports the specified agent from a ZIP file.
    //
    // Uploads new intents and entity types without deleting the existing ones.
    // Intents and entity types with the same name are replaced with the new
    // versions from ImportAgentRequest.
    //
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status ImportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest* request, ::google::longrunning::Operation* response);
    // Restores the specified agent from a ZIP file.
    //
    // Replaces the current agent version with a new one. All the intents and
    // entity types in the older version are deleted.
    //
    //
    // Operation <response: [google.protobuf.Empty][google.protobuf.Empty],
    //            metadata: [google.protobuf.Struct][google.protobuf.Struct]>
    virtual ::grpc::Status RestoreAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest* request, ::google::longrunning::Operation* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetAgent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest* request, ::google::cloud::dialogflow::v2beta1::Agent* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAgent(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::GetAgentRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::Agent>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SearchAgents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SearchAgents() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SearchAgents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SearchAgents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest* request, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSearchAgents(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TrainAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_TrainAgent() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_TrainAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrainAgent(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::TrainAgentRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ExportAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ExportAgent() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ExportAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExportAgent(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::ExportAgentRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ImportAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ImportAgent() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_ImportAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImportAgent(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::ImportAgentRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RestoreAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RestoreAgent() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_RestoreAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestoreAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRestoreAgent(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetAgent<WithAsyncMethod_SearchAgents<WithAsyncMethod_TrainAgent<WithAsyncMethod_ExportAgent<WithAsyncMethod_ImportAgent<WithAsyncMethod_RestoreAgent<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetAgent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest* request, ::google::cloud::dialogflow::v2beta1::Agent* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SearchAgents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SearchAgents() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SearchAgents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SearchAgents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest* request, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TrainAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_TrainAgent() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_TrainAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ExportAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ExportAgent() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ExportAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ImportAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ImportAgent() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_ImportAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RestoreAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RestoreAgent() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_RestoreAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestoreAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetAgent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::GetAgentRequest, ::google::cloud::dialogflow::v2beta1::Agent>(std::bind(&WithStreamedUnaryMethod_GetAgent<BaseClass>::StreamedGetAgent, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetAgentRequest* request, ::google::cloud::dialogflow::v2beta1::Agent* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAgent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::GetAgentRequest,::google::cloud::dialogflow::v2beta1::Agent>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SearchAgents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SearchAgents() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>(std::bind(&WithStreamedUnaryMethod_SearchAgents<BaseClass>::StreamedSearchAgents, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SearchAgents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SearchAgents(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest* request, ::google::cloud::dialogflow::v2beta1::SearchAgentsResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSearchAgents(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::SearchAgentsRequest,::google::cloud::dialogflow::v2beta1::SearchAgentsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TrainAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_TrainAgent() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::TrainAgentRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_TrainAgent<BaseClass>::StreamedTrainAgent, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_TrainAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TrainAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::TrainAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTrainAgent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::TrainAgentRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExportAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ExportAgent() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::ExportAgentRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_ExportAgent<BaseClass>::StreamedExportAgent, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ExportAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ExportAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExportAgent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::ExportAgentRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ImportAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ImportAgent() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::ImportAgentRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_ImportAgent<BaseClass>::StreamedImportAgent, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ImportAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ImportAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ImportAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedImportAgent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::ImportAgentRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RestoreAgent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RestoreAgent() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest, ::google::longrunning::Operation>(std::bind(&WithStreamedUnaryMethod_RestoreAgent<BaseClass>::StreamedRestoreAgent, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RestoreAgent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RestoreAgent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest* request, ::google::longrunning::Operation* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRestoreAgent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::RestoreAgentRequest,::google::longrunning::Operation>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetAgent<WithStreamedUnaryMethod_SearchAgents<WithStreamedUnaryMethod_TrainAgent<WithStreamedUnaryMethod_ExportAgent<WithStreamedUnaryMethod_ImportAgent<WithStreamedUnaryMethod_RestoreAgent<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetAgent<WithStreamedUnaryMethod_SearchAgents<WithStreamedUnaryMethod_TrainAgent<WithStreamedUnaryMethod_ExportAgent<WithStreamedUnaryMethod_ImportAgent<WithStreamedUnaryMethod_RestoreAgent<Service > > > > > > StreamedService;
};

}  // namespace v2beta1
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fagent_2eproto__INCLUDED
