// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2beta1/context.proto
// Original file comments:
// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fcontext_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fcontext_2eproto__INCLUDED

#include "google/cloud/dialogflow/v2beta1/context.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace google {
namespace cloud {
namespace dialogflow {
namespace v2beta1 {

// Manages contexts.
//
//
// Refer to [documentation](https://dialogflow.com/docs/contexts) for more
// # details about contexts.
//
// Standard methods.
class Contexts final {
 public:
  static constexpr char const* service_full_name() {
    return "google.cloud.dialogflow.v2beta1.Contexts";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of all contexts in the specified session.
    virtual ::grpc::Status ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::google::cloud::dialogflow::v2beta1::ListContextsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>> AsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>>(AsyncListContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>> PrepareAsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>>(PrepareAsyncListContextsRaw(context, request, cq));
    }
    // Retrieves the specified context.
    virtual ::grpc::Status GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::google::cloud::dialogflow::v2beta1::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>> AsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>>(AsyncGetContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>> PrepareAsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>>(PrepareAsyncGetContextRaw(context, request, cq));
    }
    // Creates a context.
    virtual ::grpc::Status CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::google::cloud::dialogflow::v2beta1::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>> AsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>>(AsyncCreateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>> PrepareAsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>>(PrepareAsyncCreateContextRaw(context, request, cq));
    }
    // Updates the specified context.
    virtual ::grpc::Status UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::google::cloud::dialogflow::v2beta1::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>> AsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>>(AsyncUpdateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>> PrepareAsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>>(PrepareAsyncUpdateContextRaw(context, request, cq));
    }
    // Deletes the specified context.
    virtual ::grpc::Status DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteContextRaw(context, request, cq));
    }
    // Deletes all active contexts in the specified session.
    virtual ::grpc::Status DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteAllContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteAllContextsRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>* AsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>* PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>* AsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>* PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>* AsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>* PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>* AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::dialogflow::v2beta1::Context>* PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::google::cloud::dialogflow::v2beta1::ListContextsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>> AsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>>(AsyncListContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>> PrepareAsyncListContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>>(PrepareAsyncListContextsRaw(context, request, cq));
    }
    ::grpc::Status GetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::google::cloud::dialogflow::v2beta1::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>> AsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>>(AsyncGetContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>> PrepareAsyncGetContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>>(PrepareAsyncGetContextRaw(context, request, cq));
    }
    ::grpc::Status CreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::google::cloud::dialogflow::v2beta1::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>> AsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>>(AsyncCreateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>> PrepareAsyncCreateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>>(PrepareAsyncCreateContextRaw(context, request, cq));
    }
    ::grpc::Status UpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::google::cloud::dialogflow::v2beta1::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>> AsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>>(AsyncUpdateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>> PrepareAsyncUpdateContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>>(PrepareAsyncUpdateContextRaw(context, request, cq));
    }
    ::grpc::Status DeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteContext(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteContextRaw(context, request, cq));
    }
    ::grpc::Status DeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteAllContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteAllContexts(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteAllContextsRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>* AsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>* PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>* AsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>* PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>* AsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>* PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>* AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2beta1::Context>* PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListContexts_;
    const ::grpc::internal::RpcMethod rpcmethod_GetContext_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateContext_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateContext_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteContext_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteAllContexts_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of all contexts in the specified session.
    virtual ::grpc::Status ListContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest* request, ::google::cloud::dialogflow::v2beta1::ListContextsResponse* response);
    // Retrieves the specified context.
    virtual ::grpc::Status GetContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response);
    // Creates a context.
    virtual ::grpc::Status CreateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response);
    // Updates the specified context.
    virtual ::grpc::Status UpdateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response);
    // Deletes the specified context.
    virtual ::grpc::Status DeleteContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest* request, ::google::protobuf::Empty* response);
    // Deletes all active contexts in the specified session.
    virtual ::grpc::Status DeleteAllContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ListContexts() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest* request, ::google::cloud::dialogflow::v2beta1::ListContextsResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContexts(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::ListContextsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::ListContextsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetContext() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::GetContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateContext() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::CreateContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateContext() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::UpdateContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::dialogflow::v2beta1::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteContext() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContext(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::DeleteContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAllContexts(::grpc::ServerContext* context, ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListContexts<WithAsyncMethod_GetContext<WithAsyncMethod_CreateContext<WithAsyncMethod_UpdateContext<WithAsyncMethod_DeleteContext<WithAsyncMethod_DeleteAllContexts<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ListContexts() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest* request, ::google::cloud::dialogflow::v2beta1::ListContextsResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetContext() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateContext() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateContext() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteContext() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ListContexts() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::ListContextsRequest, ::google::cloud::dialogflow::v2beta1::ListContextsResponse>(std::bind(&WithStreamedUnaryMethod_ListContexts<BaseClass>::StreamedListContexts, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::ListContextsRequest* request, ::google::cloud::dialogflow::v2beta1::ListContextsResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListContexts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::ListContextsRequest,::google::cloud::dialogflow::v2beta1::ListContextsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetContext() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::GetContextRequest, ::google::cloud::dialogflow::v2beta1::Context>(std::bind(&WithStreamedUnaryMethod_GetContext<BaseClass>::StreamedGetContext, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::GetContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::GetContextRequest,::google::cloud::dialogflow::v2beta1::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CreateContext() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::CreateContextRequest, ::google::cloud::dialogflow::v2beta1::Context>(std::bind(&WithStreamedUnaryMethod_CreateContext<BaseClass>::StreamedCreateContext, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::CreateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::CreateContextRequest,::google::cloud::dialogflow::v2beta1::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_UpdateContext() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::UpdateContextRequest, ::google::cloud::dialogflow::v2beta1::Context>(std::bind(&WithStreamedUnaryMethod_UpdateContext<BaseClass>::StreamedUpdateContext, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::UpdateContextRequest* request, ::google::cloud::dialogflow::v2beta1::Context* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::UpdateContextRequest,::google::cloud::dialogflow::v2beta1::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_DeleteContext() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::DeleteContextRequest, ::google::protobuf::Empty>(std::bind(&WithStreamedUnaryMethod_DeleteContext<BaseClass>::StreamedDeleteContext, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteContextRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::DeleteContextRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler< ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest, ::google::protobuf::Empty>(std::bind(&WithStreamedUnaryMethod_DeleteAllContexts<BaseClass>::StreamedDeleteAllContexts, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteAllContexts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::cloud::dialogflow::v2beta1::DeleteAllContextsRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListContexts<WithStreamedUnaryMethod_GetContext<WithStreamedUnaryMethod_CreateContext<WithStreamedUnaryMethod_UpdateContext<WithStreamedUnaryMethod_DeleteContext<WithStreamedUnaryMethod_DeleteAllContexts<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListContexts<WithStreamedUnaryMethod_GetContext<WithStreamedUnaryMethod_CreateContext<WithStreamedUnaryMethod_UpdateContext<WithStreamedUnaryMethod_DeleteContext<WithStreamedUnaryMethod_DeleteAllContexts<Service > > > > > > StreamedService;
};

}  // namespace v2beta1
}  // namespace dialogflow
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fdialogflow_2fv2beta1_2fcontext_2eproto__INCLUDED
